spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url:
    hikari:
      maximum-pool-size:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port:
      host:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: email, profile
          kakao:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type:
            client-authentication-method:
            scope:
          naver:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type:
            scope:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
jwt:
  key:
open-api:
  serviceKey :
  appKey :
  appSecret :