spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url:
    hikari:
      maximum-pool-size: 20
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #format_sql: true
        #highlight_sql: true
        #use_sql_comments: true
        #dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: 6379
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
          kakao:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type:
            client-authentication-method:
            scope:
          naver:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type:
            scope:
        provider:
          kakao:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute:
          naver:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
jwt:
  key:
open-api:
  serviceKey :
  appKey :
  appSecret :